CREATE TABLE reserva
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sala_id    BIGINT                                  NOT NULL,
    usuario_id BIGINT                                  NOT NULL,
    inicio     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    fim        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status     VARCHAR(255),
    CONSTRAINT pk_reserva PRIMARY KEY (id)
);

CREATE TABLE sala
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome       VARCHAR(255)                            NOT NULL,
    capacidade INTEGER                                 NOT NULL,
    ativa      BOOLEAN,
    CONSTRAINT pk_sala PRIMARY KEY (id)
);

CREATE TABLE usuario
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome  VARCHAR(255),
    email VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);

ALTER TABLE usuario
    ADD CONSTRAINT uc_usuario_email UNIQUE (email);

ALTER TABLE reserva
    ADD CONSTRAINT FK_RESERVA_ON_SALA FOREIGN KEY (sala_id) REFERENCES sala (id);

ALTER TABLE reserva
    ADD CONSTRAINT FK_RESERVA_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES usuario (id);